name: VerificationToken
version: ${version}
main: com.tcoded.verificationToken.VerificationToken
api-version: 1.18
commands:
  mytoken:
    description: Get your token
    usage: /mytoken
    permission: verificationtoken.mytoken
    aliases: [token, secrettoken, secretcode, verificationtoken]
  checktoken:
    description: Check a token
    usage: /checktoken <token>
    permission: verificationtoken.check

permissions:
  verificationtoken.mytoken:
    description: Permission to get your token
    default: true
  verificationtoken.check:
    description: Permission to check a token
    default: op